import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import useVerifyTokenOrRedirectUser from "@utils/hooks/useVerifyTokenOrRedirectUser.js";
import LoadingSpinner from "@components/utils/LoadingSpinner";
import useLoadingState from "@utils/hooks/useLoadingState";
import CardSection from "@components/card/CardSection";
import Banner from "@components/banner/Banner";
import Navbar from "@components/navbar/Navbar";
import styles from "@styles/Home.module.css";
import {
  getWatchAgainVideos,
  getPopularVideos,
  getVideos,
} from "@utils/videos";

export const getServerSideProps = async (context) => {
  const { userId, token } = await useVerifyTokenOrRedirectUser(context);

  const watchAgainVideos = await getWatchAgainVideos(token, userId);
  const ProductivityVideos = await getVideos("Productiviy");
  const PopularVideos = await getPopularVideos("US");
  const DisneyVideos = await getVideos("Disney");
  const MarvelVideos = await getVideos("Marvel");

  return {
    props: {
      DisneyVideos,
      MarvelVideos,
      ProductivityVideos,
      PopularVideos,
      watchAgainVideos,
    },
  };
};

export default function Home({
  DisneyVideos,
  MarvelVideos,
  ProductivityVideos,
  PopularVideos,
  watchAgainVideos,
}) {
  const loading = useLoadingState();
  return (
    <div>
      <Head>
        <title>Next Flix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <LoadingSpinner />}
      <Navbar user="" />
      <Banner
        videoId="Yj0l7iGKh8g"
        title="The Flash"
        subTitle="The fastest man alive"
        imgUrl="/static/theflashcover.jpg"
      />
      <div className={styles.sectionWrapper}>
        <CardSection title="Marvel" videos={MarvelVideos} size="large" />
        <CardSection
          title="Watch Again"
          videos={watchAgainVideos}
          size="small"
        />
        <CardSection title="Disney" videos={DisneyVideos} size="medium" />
        <CardSection title="Popular" videos={PopularVideos} size="small" />
        <CardSection
          title="Productivity"
          videos={ProductivityVideos}
          size="large"
        />
      </div>
    </div>
  );
}
