import Head from "next/head";
import Image from "next/image";

import Banner from "@components/banner/Banner";
import Navbar from "@components/navbar/Navbar";
import Card from "@components/card/Card";
import CardSection from "@components/card/CardSection";

import styles from "@styles/Home.module.css";
import { getPopularVideos, getVideos } from "lib/videos";

export const getServerSideProps = async () => {
  const allVideos = {
    popular: [
      {
        region: "US",
        result: (await getPopularVideos("US")) || [],
      },
    ],
    common: [
      {
        title: "Disney",
        result: (await getVideos("Disney")) || [],
      },
      {
        title: "Marvel",
        result: (await getVideos("Marvel")) || [],
      },
      {
        title: "Productivity",
        result: (await getVideos("Productivity")) || [],
      },
    ],
  };

  return {
    props: { allVideos },
  };
};

export default function Home({ allVideos }) {
  const commonCards = allVideos.common.map((video) => {
    return (
      <CardSection title={video.title} videos={video.result} size="small" />
    );
  });

  const popularCards = allVideos.popular.map((video) => {
    return (
      <CardSection
        title={`Most popular in the '${video.region}'`}
        videos={video.result}
        size="medium"
      />
    );
  });

  return (
    <div>
      <Head>
        <title>Next Flix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar user="codes@company.com" />
      <Banner
        title="The Flash"
        subTitle="The fastest man alive"
        imgUrl="/static/theflashcover.jpg"
      />
      <div className={styles.sectionWrapper}>
        {popularCards}
        {commonCards}
      </div>
    </div>
  );
}
