import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import verifyTokenOrRedirectUser from "@utils/hooks/verifyTokenOrRedirectUser.js.js";
import LoadingSpinner from "@components/utils/LoadingSpinner";
import useLoadingState from "@utils/hooks/useLoadingState";
import CardSection from "@components/card/CardSection";
import Banner from "@components/banner/Banner";
import Navbar from "@components/navbar/Navbar";
import styles from "@styles/Home.module.css";
import {
  getWatchAgainVideos,
  getPopularVideos,
  getVideos,
} from "@utils/videos";

export const getServerSideProps = async (context) => {
  const { userId, token } = await verifyTokenOrRedirectUser(context);

  const watchAgainVideos = (await getWatchAgainVideos(token, userId)) || [];
  const AnimeVideos = (await getVideos("Anime Trailer")) || [];
  // const PopularVideos = await getPopularVideos("US");
  const DisneyVideos = (await getVideos("Disney Trailers")) || [];
  const MarvelVideos = (await getVideos("Marvel Trailers")) || [];
  const DcVideos = (await getVideos("DC Trailers")) || [];

  return {
    props: {
      DisneyVideos,
      MarvelVideos,
      AnimeVideos,
      DcVideos,
      watchAgainVideos,
    },
  };
};

export default function Home({
  DisneyVideos,
  MarvelVideos,
  AnimeVideos,
  DcVideos,
  watchAgainVideos,
}) {
  // const loading = useLoadingState();
  return (
    <div>
      <Head>
        <title>Trailers LiB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {loading && <LoadingSpinner />} */}
      <Navbar user="" />
      <Banner
        videoId="Yj0l7iGKh8g"
        title="The Flash"
        subTitle="The fastest man alive"
        imgUrl="/static/theflashcover.jpg"
      />
      <div className={styles.sectionWrapper}>
        <CardSection
          title="Marvel Trailers"
          videos={MarvelVideos}
          size="large"
        />
        <CardSection
          title="Watch Again"
          videos={watchAgainVideos}
          size="small"
        />
        <CardSection
          title="Disney Trailers"
          videos={DisneyVideos}
          size="medium"
        />
        <CardSection title="DC Trailers" videos={DcVideos} size="small" />
        <CardSection title="Anime Trailers" videos={AnimeVideos} size="large" />
      </div>
    </div>
  );
}
